### ISSUE TITLE
QEMU TCG plugin-based tracetesting

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-tracetest#23]
- [ ] Implement generic plugin/common code for TCG-based trace testing, see also https://github.com/BinaryAnalysisPlatform/qemu/issues/24
- [ ] Tricore by @imbillow  https://github.com/rizinorg/rz-tracetest/issues/10
- [ ] x86 by @DMaroo 
- [ ] MIPS by @wargio https://github.com/rizinorg/rz-tracetest/issues/21
- [ ] Hexagon by @Rot127 for https://github.com/rizinorg/rizin/pull/3837
